#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate kavak's self-contained Unicode XID_Start / XID_Continue tables.

kavak classifies identifier characters per UAX #31 using the XID_Start and
XID_Continue derived properties. Rather than depend on a full Unicode library,
we bake the two property's codepoint ranges into a small sorted table searched
with binary search (see src/unicode_xid.c).

Input  : UCD DerivedCoreProperties.txt  (default: scripts/ucd/DerivedCoreProperties.txt)
Output : src/unicode_xid.c              (the generated table + lookup)

The UCD file and this script are both committed so regeneration never needs the
network and is reviewable. Re-run after a deliberate Unicode version bump:

    python3 scripts/gen_xid_table.py

The Unicode version is read from the input file header and stamped into the
generated source.
"""
from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_UCD = os.path.join(HERE, "ucd", "DerivedCoreProperties.txt")
OUT_C = os.path.join(ROOT, "src", "unicode_xid.c")

PROPS = ("XID_Start", "XID_Continue")


def parse_version(path: str) -> str:
    """Pull '17.0.0' out of the '# DerivedCoreProperties-17.0.0.txt' header."""
    with open(path, encoding="utf-8") as fh:
        first = fh.readline()
    m = re.search(r"-(\d+\.\d+\.\d+)\.txt", first)
    return m.group(1) if m else "unknown"


def collect_ranges(path: str, prop: str) -> list[tuple[int, int]]:
    """Return the merged, sorted [lo, hi] ranges carrying `prop`."""
    raw: list[tuple[int, int]] = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = [p.strip() for p in line.split(";")]
            if len(parts) < 2 or parts[1] != prop:
                continue
            rng = parts[0]
            if ".." in rng:
                a, b = rng.split("..")
                lo, hi = int(a, 16), int(b, 16)
            else:
                lo = hi = int(rng, 16)
            raw.append((lo, hi))
    raw.sort()
    merged: list[tuple[int, int]] = []
    for lo, hi in raw:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], hi))
        else:
            merged.append((lo, hi))
    return merged


def emit_array(name: str, ranges: list[tuple[int, int]]) -> str:
    rows = []
    for i in range(0, len(ranges), 4):
        chunk = ranges[i:i + 4]
        rows.append("  " + " ".join(f"{{0x{lo:05X},0x{hi:05X}}}," for lo, hi in chunk))
    body = "\n".join(rows)
    return (
        f"static const kavak_xid_range {name}[] = {{\n{body}\n}};\n"
        f"#define {name.upper()}_COUNT "
        f"(sizeof {name} / sizeof {name}[0])\n"
    )


def main() -> int:
    ucd = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_UCD
    if not os.path.exists(ucd):
        sys.stderr.write(f"error: UCD file not found: {ucd}\n")
        return 1
    version = parse_version(ucd)
    start = collect_ranges(ucd, "XID_Start")
    cont = collect_ranges(ucd, "XID_Continue")
    start_cps = sum(hi - lo + 1 for lo, hi in start)
    cont_cps = sum(hi - lo + 1 for lo, hi in cont)

    out = []
    out.append("// SPDX-License-Identifier: MIT")
    out.append("/**")
    out.append(" * @file src/unicode_xid.c")
    out.append(" * @brief Unicode XID_Start / XID_Continue tables (UAX #31).")
    out.append(" *")
    out.append(f" * GENERATED by scripts/gen_xid_table.py from Unicode {version}.")
    out.append(" * Do not edit by hand; re-run the generator after a Unicode version bump.")
    out.append(f" * XID_Start: {start_cps} codepoints in {len(start)} ranges.")
    out.append(f" * XID_Continue: {cont_cps} codepoints in {len(cont)} ranges.")
    out.append(" */")
    out.append("")
    out.append('#include "unicode_xid.h"')
    out.append("")
    out.append("#include <stddef.h>")
    out.append("")
    out.append(f'#define KAVAK_UNICODE_VERSION "{version}"')
    out.append("")
    out.append("typedef struct {")
    out.append("  uint32_t lo;")
    out.append("  uint32_t hi;")
    out.append("} kavak_xid_range;")
    out.append("")
    out.append(emit_array("xid_start_ranges", start))
    out.append(emit_array("xid_continue_ranges", cont))
    out.append("/* Half-open binary search over sorted, non-overlapping inclusive ranges. */")
    out.append("static bool in_ranges(const kavak_xid_range *r, size_t n, uint32_t cp) {")
    out.append("  size_t lo = 0, hi = n;")
    out.append("  while (lo < hi) {")
    out.append("    size_t mid = lo + (hi - lo) / 2;")
    out.append("    if (cp < r[mid].lo) hi = mid;")
    out.append("    else if (cp > r[mid].hi) lo = mid + 1;")
    out.append("    else return true;")
    out.append("  }")
    out.append("  return false;")
    out.append("}")
    out.append("")
    out.append("bool kavak_xid_is_start(uint32_t cp) {")
    out.append("  return in_ranges(xid_start_ranges, XID_START_RANGES_COUNT, cp);")
    out.append("}")
    out.append("")
    out.append("bool kavak_xid_is_continue(uint32_t cp) {")
    out.append("  return in_ranges(xid_continue_ranges, XID_CONTINUE_RANGES_COUNT, cp);")
    out.append("}")
    out.append("")

    with open(OUT_C, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))

    sys.stderr.write(
        f"wrote {OUT_C}\n"
        f"  Unicode {version}: "
        f"XID_Start {start_cps} cps / {len(start)} ranges, "
        f"XID_Continue {cont_cps} cps / {len(cont)} ranges\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
